### ISSUE TITLE
❤️ from Nuxt team

### ISSUE THREAD

**Issue by pi0** [jasonujmaalvis/vue-movies#4]
Hi @jasonujmaalvis. We just made a demo public based on Vue 3 and Nuxt 3 from your project.

https://github.com/nuxt/movies

Thanks for your works and cheers ❤️  (feel free to close this issue)

**Comment by jasonujmaalvis** [comment]
WOW @pi0 this looks brilliant! I'm so happy to hear it's been useful, great work everyone 🙌
